# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - main: ./cmd/sparrow
    binary: sparrow
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v1
      - v2
      - v3


archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^third_party_proto:'
      - '^scripts:'
      - '^docs:'
